/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as RecordingsRouteImport } from './routes/recordings'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MeetingIdRouteImport } from './routes/meeting.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingsRoute = RecordingsRouteImport.update({
  id: '/recordings',
  path: '/recordings',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingIdRoute = MeetingIdRouteImport.update({
  id: '/meeting/$id',
  path: '/meeting/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/notes': typeof NotesRoute
  '/recordings': typeof RecordingsRoute
  '/settings': typeof SettingsRoute
  '/meeting/$id': typeof MeetingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/notes': typeof NotesRoute
  '/recordings': typeof RecordingsRoute
  '/settings': typeof SettingsRoute
  '/meeting/$id': typeof MeetingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/notes': typeof NotesRoute
  '/recordings': typeof RecordingsRoute
  '/settings': typeof SettingsRoute
  '/meeting/$id': typeof MeetingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/dashboard'
    | '/notes'
    | '/recordings'
    | '/settings'
    | '/meeting/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/dashboard'
    | '/notes'
    | '/recordings'
    | '/settings'
    | '/meeting/$id'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/dashboard'
    | '/notes'
    | '/recordings'
    | '/settings'
    | '/meeting/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  DashboardRoute: typeof DashboardRoute
  NotesRoute: typeof NotesRoute
  RecordingsRoute: typeof RecordingsRoute
  SettingsRoute: typeof SettingsRoute
  MeetingIdRoute: typeof MeetingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recordings': {
      id: '/recordings'
      path: '/recordings'
      fullPath: '/recordings'
      preLoaderRoute: typeof RecordingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting/$id': {
      id: '/meeting/$id'
      path: '/meeting/$id'
      fullPath: '/meeting/$id'
      preLoaderRoute: typeof MeetingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  DashboardRoute: DashboardRoute,
  NotesRoute: NotesRoute,
  RecordingsRoute: RecordingsRoute,
  SettingsRoute: SettingsRoute,
  MeetingIdRoute: MeetingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
